name: VILLAIN SPORTS
favicon: null
layout_spectrum: 0.25745
typography_spectrum: 0.38228
title: Villain Sports
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1c1c1c'
    - '#d0d0d0'
    - '#515151'
    - '#898989'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
