name: VILLAIN SPORTS
favicon: null
layout_spectrum: 0.57547358982265
typography_spectrum: 0.8014329129364341
title: Villain Sports
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1c1c1c'
    - '#d0d0d0'
    - '#515151'
    - '#898989'
  brandStrength: 0.5468345095869154
  lightness: 0.4338563638739288
  saturation: 0.9510679629165679
  rhythmicContrast: 0.9328748045954853
purpose: []
